### PR TITLE
Merge pull request #1 from UWPCE-PythonCert/master

### PR DESCRIPTION
**Pull request by gabrielx52**
update

### CODE REVIEW

**Comment by gabrielx52** [comment]
merge

**Comment by gabrielx52** [comment]
merge

**Comment by gabrielx52** [comment]
merge

**Comment by PythonCHB** [comment]
Gabriel,

Did you have some changes you wanted to merge in? (typos, suggestions,
etc...) or was this all a mistake :-)

-CHB


On Tue, Apr 26, 2016 at 5:59 PM, Gabriel Meringolo <notifications@github.com
> wrote:

> update
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2
> Commit Summary
>
>    - Merge pull request #1 from UWPCE-PythonCert/master
>
> File Changes
>
>
> Patch Links:
>
>    - https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2.patch
>    - https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2>
>



-- 
Christopher Barker, PhD

Python Language Consulting
  - Teaching
  - Scientific Software Development
  - Desktop GUI and Web Development
  - wxPython, numpy, scipy, Cython

**Comment by gabrielx52** [comment]
This was a mistake, I was attempting to sync my fork with the updates in the original.

**Comment by PythonCHB** [comment]
no problem -- just wondering.....


On Thu, Apr 28, 2016 at 12:26 PM, Gabriel Meringolo <
notifications@github.com> wrote:

> This was a mistake, I was attempting to sync my fork with the updates in
> the original.
> > On Apr 28, 2016, at 11:52 AM, "Christopher H.Barker, PhD" <
> notifications@github.com> wrote:
> >
> > Gabriel,
> >
> > Did you have some changes you wanted to merge in? (typos, suggestions,
> > etc...) or was this all a mistake :-)
> >
> > -CHB
> >
> >
> > On Tue, Apr 26, 2016 at 5:59 PM, Gabriel Meringolo <
> notifications@github.com
> > > wrote:
> >
> > > update
> > > ------------------------------
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2
> > > Commit Summary
> > >
> > > - Merge pull request #1 from UWPCE-PythonCert/master
> > >
> > > File Changes
> > >
> > >
> > > Patch Links:
> > >
> > > - https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2.patch
> > > - https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2.diff
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2>
> > >
> >
> >
> >
> > --
> > Christopher Barker, PhD
> >
> > Python Language Consulting
> > - Teaching
> > - Scientific Software Development
> > - Desktop GUI and Web Development
> > - wxPython, numpy, scipy, Cython
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/UWPCE-PythonCert/SystemDevelopment/pull/2#issuecomment-215535801>
>



-- 
Christopher Barker, PhD

Python Language Consulting
  - Teaching
  - Scientific Software Development
  - Desktop GUI and Web Development
  - wxPython, numpy, scipy, Cython

**Pull request closed without merging**
